version: "3.9"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elastic
    environment:
      - node.name=elastic1
      - cluster.name=shitlist-es-docker-cluster-
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - shitlist
  bot:
    build:
      dockerfile: ./bot/Dockerfile
      context: ./
    container_name: bot
    networks:
      - shitlist
networks:
  shitlist: {}

volumes:
  data01:
    driver: local